# Generated by Django 3.1.3 on 2020-11-13 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='categories')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='posts')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('embed', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('post_update', models.DateTimeField(auto_now=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('views', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
